{% set name = "rasterstats" %}
{% set version = "0.20.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5b8ee775e815727767e0d359c03f3dd1c7840876d1d1d0c7a5a88ecf3e492938

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<37]

requirements:
  host:
    - python
    - setuptools >=61
    - pip
    - wheel
  run:
    - python
    - shapely
    - numpy >=1.9
    - rasterio >=1.0
    - cligj >=0.4
    - fiona
    - simplejson
    - affine
    - click >7.1

# fiona._err.CPLE_OpenFailedError: $SRC_DIR/tests/data/polygons.shp: No such file or directory
{% set ignore_tests = "--ignore=tests/test_io.py" %}
# rasterio._err.CPLE_OpenFailedError: $SRC_DIR/tests/data/slope.tif: No such file or directory
{% set ignore_tests = ignore_tests + " --ignore=tests/test_point.py" %}
# $SRC_DIR/tests/data/slope.tif: No such file or directory
{% set ignore_tests = ignore_tests + " --ignore=tests/test_zonal.py" %}
# $SRC_DIR/tests/data/slope.tif: No such file or directory
{% set ignore_tests = ignore_tests + " --ignore=tests/test_cli.py" %}
# $SRC_DIR/tests/data/slope.tif: No such file or directory
{% set tests_to_skip = "test_csv or test_categorical_csv" %}

test:
  source_files:
    - tests
  imports:
    - rasterstats
  commands:
    - rio zonalstats --help
    - rio pointquery --help
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v {{ignore_tests}} -k "not ({{ tests_to_skip }})" tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/perrygeo/python-rasterstats
  license: BSD-3-Clause
  license_family: MIT
  license_file: LICENSE.txt
  summary: Summarize geospatial raster datasets based on vector geometries
  description: |
    rasterstats is a Python module for summarizing geospatial raster datasets based on vector geometries.
    It includes functions for zonal statistics and interpolated point queries. 
    The command-line interface allows for easy interoperability with other GeoJSON tools.
  doc_url: https://pythonhosted.org/rasterstats
  dev_url: https://github.com/perrygeo/python-rasterstats

extra:
  recipe-maintainers:
    - perrygeo
    - ocefpaf