{% set version = "0.12.0" %}

package:
  name: rasterstats
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/rasterstats/rasterstats-{{ version }}.tar.gz
  sha256: ec202b0b405f4f2cff9ab0e1ba06625512eb82a631a56a0f15e434d24d5dcb8f

build:
  number: 2
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - shapely
    - numpy >=1.9
    - rasterio >=0.27
    - cligj >=0.4
    - fiona
    - simplejson

test:
  imports:
    - rasterstats
  commands:
    - rio zonalstats --help
    - rio pointquery --help

about:
  home: https://github.com/perrygeo/python-raster-stats
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Summarize geospatial raster datasets based on vector geometries.'

extra:
  recipe-maintainers:
    - perrygeo
    - ocefpaf
