{% set version = "0.11" %}

package:
  name: rasterstats
  version: {{ version }}

source:
  fn: rasterstats-{{ version }}.tar.gz
  url: https://github.com/perrygeo/python-rasterstats/archive/{{ version }}.tar.gz
  sha256: 0de3487986cb43f19613c653c170091d42b6f460aa7f3270f1646955faf6d5dd

build:
  number: 0
  preserve_egg_dir: True
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - shapely
    - numpy >=1.9
    - rasterio >=0.27
    - cligj >=0.4
    - fiona
    - simplejson
    - gdal 2.1.*

test:
  imports:
    - rasterstats
  commands:
    - rio zonalstats --help
    - rio pointquery --help

about:
  home: https://github.com/perrygeo/python-raster-stats
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Summarize geospatial raster datasets based on vector geometries.'

extra:
  recipe-maintainers:
    - perrygeo
    - ocefpaf
