{% set version = "0.13.0" %}

package:
  name: rasterstats
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/rasterstats/rasterstats-{{ version }}.tar.gz
  sha256: 8d2a59bdcf1ebf882ecbb2f511b180f05c14b0b70813d4a805cd91c4326765b7

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - shapely
    - numpy >=1.9
    - rasterio >=0.27
    - cligj >=0.4
    - fiona
    - simplejson

test:
  imports:
    - rasterstats
  commands:
    - rio zonalstats --help
    - rio pointquery --help

about:
  home: https://github.com/perrygeo/python-raster-stats
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Summarize geospatial raster datasets based on vector geometries.'

extra:
  recipe-maintainers:
    - perrygeo
    - ocefpaf
