travis:
  secure:
    BINSTAR_TOKEN: RywTPojQzUcK+MLppbW1wHulS/NmDAPoBjWfFYBS5nCjqDb03DXUc+67GaNo2v4h/opryGw69PjNRT/y0I5si9ntpzWhsWOc99lEsHC/+4gkAwvUkGqw/4RMJl8HCaR25gjd761Y4bpHbKwqZn4v1ypoVCf3qND1B74Swwrr75UZf96dMOrYspXZ/u0bYrmd430Xhk+1wkt3/DWaA9Wtde8DwNSn5twTyluvSFa4nIadnWpUvuMpIgeF2292CTa1SH/tXlGftrv2CgZ8RLziJcXlolLtd+xyVRoc6Hxpp9xvOX8kojAkMMzk869HpUHifuAFefFrljPKgeaYrXWCwxYB9SuQVyzvgp4ma2DENgaKz8zWDjxAG12upQwqGmxKHK0wtdF1QnkWLIvz8v6kToBRwxcdeSaXbE1hAFUPuP37/Hbj5v0fgT3mDWOeiSOoxFFgu6rDibW1b81AfLO52X5McoDOWzv9p/tVPxcrflZlW80T87DDz2U/GG8ngpPE2a6AE1+84OsylXCMl2yIsBvHzKpUTSurQhvZgf1/9oxUlb9OGSS8TJ3/CvjKnpykTSv/iR68OCS9MHJK37R5Tz07bPuoi7lD78T59FO2M7W3Gqk+FqQs0X7bAdTiZqVRmgwEr8j+BeQGmz7EQteN/5ueKKABd2CutVaN4Cmzl+4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
